services:
  - type: web
    name: vehicle-classifier-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app 
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

  - type: web
    name: vehicle-classifier-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app/streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
